export const GET_UNITS = 'GET_UNITS';
export const GET_UNITS_FAILURE = 'GET_UNITS_FAILURE';
export const GET_UNITS_SUCCESS = 'GET_UNITS_SUCCESS';
export const FILTER_UNIT = 'FILTER_UNIT';
export const SET_UNIT_DETAIL = 'SET_UNIT_DETAIL';